version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: laritech_farms
      POSTGRES_USER: laritech_user
      POSTGRES_PASSWORD: laritech_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laritech_user -d laritech_farms"]
      interval: 30s
      timeout: 10s
      retries: 3

  # LariTechFarms API
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://laritech_user:laritech_password@db:5432/laritech_farms
      JWT_SECRET: your-super-secret-jwt-key-change-this
      ALLOWED_ORIGINS: http://localhost:4200,http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm start
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@laritech.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    profiles:
      - tools

volumes:
  postgres_data:
